---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/name: tenant-abc
    app.kubernetes.io/component: tenant-management
    app.kubernetes.io/part-of: platform-management

resources:

# install cluster specific applications
helmGlobals:
  chartHome: ../../helm-charts
helmCharts:
- name: tenant
  version: 1.0.0
  valuesFile: tenant-values.yaml
